@UrlShortenerService_HostAddress = http://localhost:5134

# Tạo URL rút gọn
POST {{UrlShortenerService_HostAddress}}/api/urls
Content-Type: application/json

{
  "originalUrl": "https://example.com",
  "userId": "user123",
  "expiresAt": "2024-08-31T00:00:00Z"
}

###

# Kiểm tra trạng thái service
GET {{UrlShortenerService_HostAddress}}/api/urls/health
Accept: application/json

###