name: CI API Gateway
on:
  push:
    paths:
      - 'src/ApiGateway/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore dependencies
        run: dotnet restore src/ApiGateway/ApiGateway.csproj
      - name: Build
        run: dotnet build --no-restore src/ApiGateway/ApiGateway.csproj
      - name: Test
        run: echo "No tests yet" 