name: CI Notification Service
on:
  push:
    paths:
      - 'src/NotificationService/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install --prefix src/NotificationService
      - name: Lint
        run: npm run lint --prefix src/NotificationService || echo "No lint script"
      - name: Test
        run: npm test --prefix src/NotificationService || echo "No test script" 